#!/bin/bash

read intf<./interface_act

echo "Desactivando monitor...">status
ip link set dev $intf down
sleep 3

iw dev $intf set type managed
sleep 3

ip link set dev $intf up
sleep 3
echo "OK">status

exit 0
